In [2]:
import pandas as pd
import sqlite3
import matplotlib.pyplot as plt
import numpy as np
import re
import seaborn as sns
import time
import requests
from sklearn.preprocessing import LabelEncoder
from scipy import stats
from sklearn.preprocessing import LabelEncoder

pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('./fires_in_ph_clean_3.0.csv')

In [4]:
len(df)

168438

250 buildings have lost over 90% of the total money lost in fires

In [5]:
prop_cols = [x for x in df.columns if 'prop_loss_' in x]
cont_cols = [x for x in df.columns if 'cont_loss_' in x]
df['total_prop_loss'] = df[prop_cols].sum(axis=1)
df['total_cont_loss'] = df[cont_cols].sum(axis=1)
df['total_money_lost'] = df.total_prop_loss + df.total_cont_loss
df = df.sort_values('total_money_lost', ascending=False)
df['cumulative_money_lost'] = df['total_money_lost'].cumsum()
df['cumulative_percent_money_lost'] = df.cumulative_money_lost / df.total_money_lost.sum()
df.cumulative_percent_money_lost.head(230)

110881    0.289767
147569    0.342890
119885    0.371833
59598     0.398534
79915     0.422653
            ...
94033     0.846878
69782     0.847601
78683     0.848325
106285    0.849049
9840      0.849772
Name: cumulative_percent_money_lost, Length: 230, dtype: float64

In [8]:
df[cont_cols].sum()

cont_loss_2012    10487476.0
cont_loss_2013      416729.0
cont_loss_2014      426195.0
cont_loss_2015      609315.0
cont_loss_2016      638100.0
cont_loss_2017      944080.0
cont_loss_2018      955211.0
cont_loss_2019      558549.0
cont_loss_2020      603545.0
cont_loss_2021      887864.0
dtype: float64

In [236]:
len(df[df.total_money_lost > 0]) / len(df)

0.009926501145822202

150 out of about 150,000 buildings have had about half of the identified fires.

In [ ]:
fire_cols = [x for x in df.columns if 'building_fire' in x]
df['total_fires'] = df[fire_cols].sum(axis=1)
df = df.sort_values('total_fires', ascending=False)
df['cumulative_fires'] = df['total_fires'].cumsum()
df['cumulative_percent_fires'] = df.cumulative_fires / df.total_fires.sum()
df.cumulative_percent_fires.head(150)

31835     0.032552
144487    0.053914
16820     0.073298
3045      0.092625
76538     0.111613
            ...
60256     0.501837
64206     0.502910
130929    0.503928
161494    0.504945
92724     0.505962
Name: cumulative_percent_fires, Length: 150, dtype: float64

About 1000 buildings caused 80% of fires.

In [ ]:
display(df.cumulative_percent_fires.head(1000))

31835     0.032552
144487    0.053914
16820     0.073298
3045      0.092625
76538     0.111613
            ...
152407    0.790449
54742     0.790562
8896      0.790675
126288    0.790788
110067    0.790901
Name: cumulative_percent_fires, Length: 1000, dtype: float64

Only about 2% of buildings have ever had a fire.

In [ ]:
df['at_least_one_fire'] = df.total_fires > 0
df.at_least_one_fire.sum() / len(df)

0.025724598962229426

In [ ]:
len(df[
    (df.building_fires_2012 > 0)
])

586

In [ ]:
len(df[
    (df.building_fires_2012 > 0) |
    (df.building_fires_2013 > 0)

])

1073

In [ ]:
len(df[
    (df.building_fires_2012 > 0) |
    (df.building_fires_2013 > 0) |
    (df.building_fires_2014 > 0)
])

1518

In [ ]:
len(df[
    (df.building_fires_2012 > 0) |
    (df.building_fires_2013 > 0) |
    (df.building_fires_2014 > 0) |
    (df.building_fires_2015 > 0)

])

1923

In [ ]:
len(df[
    (df.building_fires_2012 > 0) |
    (df.building_fires_2013 > 0) |
    (df.building_fires_2014 > 0) |
    (df.building_fires_2015 > 0) |
    (df.building_fires_2016 > 0)
])

2335

In [ ]:
len(df[
    (df.building_fires_2012 > 0) |
    (df.building_fires_2013 > 0) |
    (df.building_fires_2014 > 0) |
    (df.building_fires_2015 > 0) |
    (df.building_fires_2016 > 0)   | (df.building_fires_2017 > 0)

])

2779

In [ ]:
len(df[
    (df.building_fires_2012 > 0) |
    (df.building_fires_2013 > 0) |
    (df.building_fires_2014 > 0) |
    (df.building_fires_2015 > 0) |
    (df.building_fires_2016 > 0)   | 
    (df.building_fires_2017 > 0) |
        (df.building_fires_2018 > 0)


])

3196

In [ ]:
len(df[
    (df.building_fires_2012 > 0) |
    (df.building_fires_2013 > 0) |
    (df.building_fires_2014 > 0) |
    (df.building_fires_2015 > 0) |
    (df.building_fires_2016 > 0)   | 
    (df.building_fires_2017 > 0) |
        (df.building_fires_2018 > 0) |
        (df.building_fires_2019 > 0)


])

3576

In [ ]:
len(df[
    (df.building_fires_2012 > 0) |
    (df.building_fires_2013 > 0) |
    (df.building_fires_2014 > 0) |
    (df.building_fires_2015 > 0) |
    (df.building_fires_2016 > 0)   | 
    (df.building_fires_2017 > 0) |
        (df.building_fires_2018 > 0) |
        (df.building_fires_2019 > 0) |
        (df.building_fires_2020 > 0)


])

3944

In [ ]:
len(df[
    (df.building_fires_2012 > 0) |
    (df.building_fires_2013 > 0) |
    (df.building_fires_2014 > 0) |
    (df.building_fires_2015 > 0) |
    (df.building_fires_2016 > 0)   | 
    (df.building_fires_2017 > 0) |
    (df.building_fires_2018 > 0) |
    (df.building_fires_2019 > 0) |
    (df.building_fires_2020 > 0) |

        (df.building_fires_2021 > 0)

])

4333

In [ ]:
len(df[df['building_fires_2021'] > 0])

700

In [ ]:
columns_to_sum = [f"building_fires_{year}" for year in range(2012, 2022)]  # This creates a list of column names for the years 2012 through 2021
df['total_fires'] = df[columns_to_sum].sum(axis=1)

In [225]:
df.sort_values('total_fires', ascending=False).head(2)

,corrected_address,corrected_unit,std_city,std_st,std_zip5,project_name,building_name,total_dwelling_units,acc_units,total_occupied,regular_vacant,total_units,number_reported,people_per_unit,people_total,chldrn_mbr_cnt,std_zip9,dofa_actual_year,construction_year,months_since_report,rent_per_month,spending_per_month,spending_per_month_prev_yr,hh_income,person_income,months_waiting,months_from_movein,ave_util_allow,tminority,tpoverty,eldly_prcnt,median_inc_amnt,dpvact,dpvnost,msa_nm,metro,micro,dpv,dpvrc,msgusps,annl_expns_amnt,annl_expns_amnt_prev_yr,pha_total_units,rad_chap_indr_N,rad_chap_indr_Y,rad_type_,rad_type_PBRA,rad_type_PBV,rad_type_PBV/PBRA,msg2kx_** Centroid Lat/Long **,msg2kx_** No Lat/Longs gen'd **,msg2kx_** Street-Level Rooftop **,std_st_AK,std_st_AL,std_st_AR,std_st_AZ,std_st_CA,std_st_CO,std_st_CT,std_st_DC,std_st_DE,std_st_FL,std_st_GA,std_st_GU,std_st_HI,std_st_IA,std_st_ID,std_st_IL,std_st_IN,std_st_KS,std_st_KY,std_st_LA,std_st_MA,std_st_MD,std_st_ME,std_st_MI,std_st_MISSING_VALUE,std_st_MN,std_st_MO,std_st_MS,std_st_MT,std_st_NC,std_st_ND,std_st_NE,std_st_NH,std_st_NJ,std_st_NM,std_st_NV,std_st_NY,std_st_OH,std_st_OK,std_st_OR,std_st_PA,std_st_PR,std_st_RI,std_st_SC,std_st_SD,std_st_TN,std_st_TX,std_st_UT,std_st_VA,std_st_VI,std_st_VT,std_st_WA,std_st_WI,std_st_WV,std_st_WY,building_type_code_ES,building_type_code_NDS,building_type_code_RW,building_type_code_SD,building_type_code_SF,building_type_code_WU,building_status_type_code_DDAPRD,building_status_type_code_DDDRFT,building_status_type_code_DDPROP,building_status_type_code_INAPCP,building_status_type_code_RMI,building_status_type_code_RMIPRP,addr_type_F,addr_type_G,addr_type_H,addr_type_MISSING_VALUE,addr_type_P,addr_type_R,addr_type_S,apt_type_#,apt_type_Apt,apt_type_Lot,apt_type_MISSING_VALUE,apt_type_Ste,apt_type_Unit,zip_class_MISSING_VALUE,zip_class_P,zip_class_U,lvl2kx_4,lvl2kx_5,lvl2kx_B,lvl2kx_MISSING_VALUE,lvl2kx_R,lvl2kx_T,ur_MISSING_VALUE,ur_R,ur_U,pct_occupied,pct_reported,pct_movein,pct_lt5k,pct_5k_lt10k,pct_10k_lt15k,pct_15k_lt20k,pct_ge20k,pct_wage_major,pct_welfare_major,pct_other_major,pct_median,pct_lt50_median,pct_lt30_median,pct_2adults,pct_1adult,pct_female_head,pct_female_head_child,pct_disabled_lt62,pct_disabled_ge62,pct_disabled_all,pct_lt24_head,pct_age25_50,pct_age51_61,pct_age62plus,pct_age85plus,pct_minority,pct_black,pct_native_american,pct_asian,pct_hispanic,pct_utility_allow,pct_bed1,pct_bed2,pct_bed3,pct_overhoused,tpct_ownsfd,pct_disabled_lt62_all,pct_lt80_median,building_fires_2012,building_fires_2013,building_fires_2014,building_fires_2015,building_fires_2016,building_fires_2017,building_fires_2018,building_fires_2019,building_fires_2020,building_fires_2021,prop_loss_2012,prop_loss_2013,prop_loss_2014,prop_loss_2015,prop_loss_2016,prop_loss_2017,prop_loss_2018,prop_loss_2019,prop_loss_2020,prop_loss_2021,cont_loss_2012,cont_loss_2013,cont_loss_2014,cont_loss_2015,cont_loss_2016,cont_loss_2017,cont_loss_2018,cont_loss_2019,cont_loss_2020,cont_loss_2021,oth_death_2012,oth_death_2013,oth_death_2014,oth_death_2015,oth_death_2016,oth_death_2017,oth_death_2018,oth_death_2019,oth_death_2020,oth_death_2021,oth_inj_2012,oth_inj_2013,oth_inj_2014,oth_inj_2015,oth_inj_2016,oth_inj_2017,oth_inj_2018,oth_inj_2019,oth_inj_2020,oth_inj_2021,total_fires
140003,630 W STATE ST,NaN,TRENTON,NJ,8618.0,2670,28200,150,150,135,15,151,134,1.0,139.0,0.0,5572.0,1971.0,1970.0,7.0,319.0,1043.0,935.0,13552.0,13064.0,49.0,95.0,0.0,96.660004,47.209999,56.830002,10704.0,NaN,NaN,277.0,1.0,0.0,NaN,NaN,8.0,1689785.0,1560029.0,1495.0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,1,89.400002,99.260002,14.93,1.5,9.77,66.169998,11.28,11.28,5.97,0.0,93.279999,11.75,98.510002,94.029999,0.0,0.0,47.009998,0.0,82.139999,58.970001,66.190002,0.0,5.22,36.570000,58.209999,2.24,91.040001,77.610001,0.00,0.00,13.430000,0.0,100.0,0.0,0.0,0.0,5.070000,33.810001,100.0,58.0,56.0,71.0,45.0,37.0,43.0,17.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,329.0
104184,3700 NEW JERSEY AVE,NaN,WILDWOOD,NJ,8260.0,4620,35719,98,98,95,3,100,95,1.0,96.0,0.0,6154.0,1977.0,NaN,0.0,368.0,580.0,526.0,15416.0,15255.0,0.0,84.0,0.0,45.490002,24.030001,70.830002,11909.0,NaN,NaN,17.0,1.0,0.0,NaN,NaN,8.0,660687.0,605672.0,168.0,1,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,1,95.000000,100.000000,15.79,0.0,3.16,56.840000,23.16,16.84,1.05,0.0,98.949997,15.29,98.949997,83.160004,0.0,0.0,47.369999,0.0,100.000000,82.089996,86.459999,0.0,0.00,29.469999,70.529999,3.16,42.110001,21.049999,1.05,2.11,17.889999,0.0,100.0,0.0,0.0,0.0,28.940001,29.170000,100.0,17.0,12.0,16.0,14.0,27.0,10.0,14.0,3.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,15.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117.0

In [228]:
conn = sqlite3.Connection('./data/nfirs/fire_data.db')
d = pd.read_sql("""
    select *
    from incident_address ia
        join basic_incident bi using (INCIDENT_KEY)
    where ia.STATE = 'NJ' and
        UPPER(ia.NUM_MILE) = '3700' and
        UPPER(ia.CITY) = 'WILDWOOD'
""", conn)
d

,ID,INCIDENT_KEY,STATE,FDID,INC_DATE,INC_NO,EXP_NO,LOC_TYPE,NUM_MILE,STREET_PRE,STREETNAME,STREETTYPE,STREETSUF,APT_NO,CITY,STATE_ID,ZIP5,ZIP4,X_STREET,ID,STATE,FDID,INC_DATE,INC_NO,EXP_NO,VERSION,DEPT_STA,INC_TYPE,ADD_WILD,AID,ALARM,ARRIVAL,INC_CONT,LU_CLEAR,SHIFT,ALARMS,DISTRICT,ACT_TAK1,ACT_TAK2,ACT_TAK3,APP_MOD,SUP_APP,EMS_APP,OTH_APP,SUP_PER,EMS_PER,OTH_PER,RESOU_AID,PROP_LOSS,CONT_LOSS,PROP_VAL,CONT_VAL,FF_DEATH,OTH_DEATH,FF_INJ,OTH_INJ,DET_ALERT,HAZ_REL,MIXED_USE,PROP_USE,CENSUS
0,1185014,NJ_05002_10032021_1261_0,NJ,5002,10032021,1261,0,1,3700,None,New Jersey,AVE,None,201,WILDWOOD,NJ,8260,None,None,1185014,NJ,5002,10032021,1261,0,5.0,2,113,N,4,100320212059,100320212104,None,1.003202e+11,A,NaN,2.0,73.0,74.0,NaN,Y,1,0,1,4,0,1,N,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,None,None,None,429,NaN
1,1185020,NJ_05002_10152021_1299_0,NJ,5002,10152021,1299,0,1,3700,None,New Jersey,AVE,None,None,WILDWOOD,NJ,8260,None,None,1185020,NJ,5002,10152021,1299,0,5.0,2,424,N,N,101520212346,101520212351,None,1.016202e+11,D,NaN,31.0,51.0,86.0,NaN,Y,0,0,2,0,0,5,N,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,None,None,None,460,NaN
2,1185022,NJ_05002_10242021_1324_0,NJ,5002,10242021,1324,0,1,3700,None,New Jersey,AVE,None,None,WILDWOOD,NJ,8260,None,None,1185022,NJ,5002,10242021,1324,0,5.0,2,412,N,4,102420211157,102420211202,None,1.024202e+11,B,NaN,2.0,42.0,NaN,NaN,Y,1,0,1,5,0,1,N,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,None,None,None,429,NaN
3,1185073,NJ_05003_10242021_0001379_0,NJ,5003,10242021,1379,0,1,3700,None,New Jersey,AVE,None,None,WILDWOOD,NJ,8260,None,None,1185073,NJ,5003,10242021,1379,0,5.0,003,412,N,2,102420211157,102420211200,None,1.024202e+11,None,1.0,3.0,86.0,NaN,NaN,N,1,1,0,6,1,0,N,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,None,None,None,429,NaN
4,3346293,NJ_05002_01212020_43_0,NJ,5002,1212020,43,0,1,3700,None,New Jersey,AVE,None,6th Floor,WILDWOOD,NJ,8260,None,None,3346293,NJ,5002,1212020,43,0,5.0,2,113,N,4,12120201015,12120201015.0,None,1.212020e+10,A,NaN,31.0,73.0,75.0,74.0,Y,2,0,0,4,0,0,N,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,1,None,None,429,214.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272,20718601,NJ_05003_11122012_0003184_0,NJ,5003,11122012,3184,0,1,3700,None,NEW JERSEY,AVE,None,1001,WILDWOOD,NJ,8260,None,None,20718601,NJ,5003,11122012,3184,0,5.0,WFD,113,N,2,111220121253,111220121255.0,None,1.112201e+11,D,1.0,3.0,81.0,87.0,NaN,Y,2,2,0,3,0,0,N,0.0,5.0,NaN,NaN,0.0,NaN,0.0,NaN,1,None,NN,429,21501.0
273,20718613,NJ_05003_12072012_0003371_0,NJ,5003,12072012,3371,0,1,3700,None,NEW JERSEY,AVE,None,801,WILDWOOD,NJ,8260,None,None,20718613,NJ,5003,12072012,3371,0,5.0,WFD,113,N,N,120720122321,120720122323.0,None,1.207201e+11,C,1.0,3.0,51.0,63.0,NaN,Y,2,2,0,3,0,0,N,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,2,None,NN,429,NaN
274,20718616,NJ_05003_12142012_0003404_0,NJ,5003,12142012,3404,0,1,3700,None,NEW JERSEY,AVE,None,1010,WILDWOOD,NJ,8260,None,None,20718616,NJ,5003,12142012,3404,0,5.0,WFD,113,N,2,121420122046,121420122049.0,None,1.214201e+11,C,1.0,3.0,86.0,81.0,51.0,Y,2,2,0,3,0,0,N,0.0,0.0,NaN,NaN,0.0,NaN,0.0,NaN,1,None,NN,429,21402.0
275,20718623,NJ_05003_12252012_0003481_0,NJ,5003,12252012,3481,0,1,3700,None,NEW JERSEY,AVE,None,506,WILDWOOD,NJ,8260,None,None,20718623,NJ,5003,12252012,3481,0,5.0,WFD,113,N,2,122520122038,122520122041.0,None,1.225201e+11,D,1.0,3.0,81.0,87.0,51.0,Y,2,2,0,3,0,0,N,0.0,5.0,NaN,NaN,0.0,NaN,0.0,NaN,1,None,NN,429,21501.0
276,20718624,NJ_05003_12252012_0003482_0,NJ,5003,12252012,3482,0,1,3700,None,NEW JERSEY,AVE,None,601,WILDWOOD,NJ,8260,None,None,20718624,NJ,5003,12252012,3482,0,5.0,WFD,113,N,2,122520122045,122520122046.0,None,1.225201e+11,D,1.0,3.0,81.0,86.0,NaN,Y,2,2,0,3,0,0,N,0.0,1.0,NaN,NaN,0.0,NaN,0.0,NaN,1,None,NN,429,21501.0

In [170]:
state = d[(d.NUM_MILE == 630)&(d.STREETNAME == 'STATE')]
state.groupby('INC_TYPE').size()

INC_TYPE
111      1
113    381
118      1
412      7
421      1
445      1
dtype: int64

In [176]:
state.ALARM.nunique() / len(state)

1.0

In [218]:
state['inc_month'] = state.iloc[:, 4].apply(lambda x: str(x)[:1] if len(str(x)) == 7 else str(x)[:2])

C:\Users\jackv\AppData\Local\Temp\ipykernel_3588\3316352990.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  state['inc_month'] = state.iloc[:, 4].apply(lambda x: str(x)[:1] if len(str(x)) == 7 else str(x)[:2])

In [217]:
state['inc_day'] = state.iloc[:, 4].apply(lambda x: str(x)[-6:-4])

C:\Users\jackv\AppData\Local\Temp\ipykernel_3588\2667550216.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  state['inc_day'] = state.iloc[:, 4].apply(lambda x: str(x)[-6:-4])

In [189]:
state['inc_year'] = state.iloc[:, 4].apply(lambda x: str(x)[-4:])

C:\Users\jackv\AppData\Local\Temp\ipykernel_3588\1103108140.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  state['inc_year'] = state.iloc[:, 4].apply(lambda x: str(x)[-4:])

In [190]:
state.groupby('inc_year').size()

inc_year
2012    70
2013    70
2014    93
2015    53
2016    37
2017    44
2018    17
2020     7
2021     1
dtype: int64

In [224]:
state.groupby('ACT_TAK1').size().sort_values(ascending=False)

ACT_TAK1
86.0    214
51.0    103
63.0     53
80.0     11
87.0      5
11.0      2
60.0      2
41.0      1
61.0      1
dtype: int64

In [227]:
pd.set_option('display.max_rows', 10)
state.sort_values(['inc_year', 'inc_month', 'inc_day'])

,ID,INCIDENT_KEY,STATE,FDID,INC_DATE,INC_NO,EXP_NO,LOC_TYPE,NUM_MILE,STREET_PRE,STREETNAME,STREETTYPE,STREETSUF,APT_NO,CITY,STATE_ID,ZIP5,ZIP4,X_STREET,ID,STATE,FDID,INC_DATE,INC_NO,EXP_NO,VERSION,DEPT_STA,INC_TYPE,ADD_WILD,AID,ALARM,ARRIVAL,INC_CONT,LU_CLEAR,SHIFT,ALARMS,DISTRICT,ACT_TAK1,ACT_TAK2,ACT_TAK3,APP_MOD,SUP_APP,EMS_APP,OTH_APP,SUP_PER,EMS_PER,OTH_PER,RESOU_AID,PROP_LOSS,CONT_LOSS,PROP_VAL,CONT_VAL,FF_DEATH,OTH_DEATH,FF_INJ,OTH_INJ,DET_ALERT,HAZ_REL,MIXED_USE,PROP_USE,CENSUS,inc_year,inc_day,inc_month
9497,20742531,NJ_11070_1122012_1200261_0,NJ,11070,1122012,1200261,0,1,630,W,STATE,ST,None,None,TRENTON,NJ,8618,NaN,COLONIAL AVE,20742531,NJ,11070,1122012,1200261,0,5.0,S8,113,N,N,11220120715,11220120718.0,11220120718.0,1.122012e+10,None,1,1st,86.0,-,None,Y,3,3,0,12,4,0,N,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,1,N,NN,429,None,2012,12,1
9502,20742536,NJ_11070_1132012_1200283_0,NJ,11070,1132012,1200283,0,1,630,W,STATE,ST,None,None,TRENTON,NJ,8618,NaN,COLONIAL AVE,20742536,NJ,11070,1132012,1200283,0,5.0,S8,113,N,N,11320120415,11320120420.0,11320120420.0,1.132012e+10,None,1,None,86.0,51,63,Y,3,3,0,12,0,0,N,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,1,N,NN,429,None,2012,13,1
9536,20742570,NJ_11070_1242012_1200510_0,NJ,11070,1242012,1200510,0,1,630,W,STATE,ST,None,None,TRENTON,NJ,8618,NaN,COLONIAL AVE,20742570,NJ,11070,1242012,1200510,0,5.0,S8,113,N,N,12420121348,12420121352.0,12420121352.0,1.242012e+10,None,1,1st,86.0,-,None,Y,3,3,0,12,4,0,N,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,1,N,NN,429,None,2012,24,1
9544,20742578,NJ_11070_1272012_1200585_0,NJ,11070,1272012,1200585,0,1,630,W,STATE,ST,None,None,TRENTON,NJ,8618,NaN,COLONIAL AVE,20742578,NJ,11070,1272012,1200585,0,5.0,S8,113,N,N,12720122042,12720122044.0,12720122044.0,1.272012e+10,None,1,TR,86.0,51,-,Y,4,4,0,16,0,0,N,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,1,N,NN,429,None,2012,27,1
9545,20742579,NJ_11070_1282012_1200593_0,NJ,11070,1282012,1200593,0,1,630,W,STATE,ST,None,None,TRENTON,NJ,8618,NaN,COLONIAL AVE,20742579,NJ,11070,1282012,1200593,0,5.0,S8,113,N,N,12820120959,12820121001.0,12820121001.0,1.282012e+10,None,1,1st,51.0,-,None,Y,3,3,0,12,4,0,N,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,1,N,NN,429,None,2012,28,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1558,3366504,NJ_11070_11262020_0006345_0,NJ,11070,11262020,6345,0,1,630,W,STATE,ST,None,None,TRENTON,NJ,8618,NaN,None,3366504,NJ,11070,11262020,6345,0,5.0,008,412,N,N,112620202042,112620202049.0,None,1.126202e+11,C,None,W,86.0,None,None,N,5,0,3,31,0,5,N,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,None,None,None,429,None,2020,26,11
462,3365402,NJ_11070_02012020_0000601_0,NJ,11070,2012020,601,0,1,630,W,STATE,ST,None,312,TRENTON,NJ,8618,NaN,None,3365402,NJ,11070,2012020,601,0,5.0,008,113,N,N,20120201351,20120201355.0,20120201400.0,2.012020e+10,D,None,W,63.0,None,None,N,6,0,1,38,0,2,N,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,1,None,None,429,None,2020,01,2
484,3365424,NJ_11070_02082020_0000740_0,NJ,11070,2082020,740,0,1,630,W,STATE,ST,None,None,TRENTON,NJ,8618,NaN,None,3365424,NJ,11070,2082020,740,0,5.0,010,113,N,N,20820200459,20820200505.0,None,2.082020e+10,B,None,W,86.0,None,None,N,5,0,1,34,0,4,N,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,U,None,None,429,None,2020,08,2
595,3365536,NJ_11070_03162020_0001456_0,NJ,11070,3162020,1456,0,1,630,W,STATE,ST,None,None,TRENTON,NJ,8601,NaN,None,3365536,NJ,11070,3162020,1456,0,5.0,010,113,N,N,31620200134,31620200139.0,None,3.162020e+10,C,None,N,63.0,None,None,N,6,0,0,36,0,0,N,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,1,None,None,429,None,2020,16,3
229,1200165,NJ_11070_05062021_0002602_0,NJ,11070,5062021,2602,0,1,630,W,STATE,ST,None,None,TRENTON,NJ,8601,NaN,None,1200165,NJ,11070,5062021,2602,0,5.0,010,113,N,N,50620210454,50620210501,None,5.062021e+10,C,None,W,63.0,None,None,N,6,0,0,30,0,0,N,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,1,None,None,429,None,2021,06,5

In [149]:
idf = pd.read_csv('./initial_df.csv')

C:\Users\jackv\AppData\Local\Temp\ipykernel_3588\1204537272.py:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  idf = pd.read_csv('./initial_df.csv')

In [150]:
idf[
(    idf.num_mile == '131'
)    &
(idf.state == 'MA')
    ]

,inc_type,num_mile,street_pre,streetname,streettype,streetsuf,apt_no,state,city,zip5,prop_loss,cont_loss,oth_death,oth_inj,ff_death,ff_inj,inc_year,address
80543,111,131,NaN,DAVENPORT,ST,NaN,NaN,MA,SPRINGFIELD,1119,30025.0,7500.0,NaN,NaN,0.0,0.0,2021,131 DAVENPORT ST
80941,111,131,NaN,WEST,RD,NaN,NaN,MA,ASHBY,1431,300000.0,75000.0,NaN,NaN,0.0,0.0,2021,131 WEST RD
81618,111,131,NaN,WEST,RD,NaN,NaN,MA,ASHBY,1431,0.0,0.0,NaN,NaN,0.0,0.0,2021,131 WEST RD
82487,111,131,NaN,PLAIN,ST,NaN,NaN,MA,ROCKLAND,2370,500.0,0.0,NaN,NaN,0.0,0.0,2021,131 PLAIN ST
82792,111,131,NaN,NEPONSET VALLEY,PKY,NaN,NaN,MA,BOSTON,2136,125000.0,25000.0,NaN,NaN,0.0,0.0,2021,131 NEPONSET VALLEY PKY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4249837,118,131,NaN,CLORAN,ST,NaN,NaN,MA,SPRINGFIELD,1109,0.0,0.0,NaN,NaN,0.0,0.0,2018,131 CLORAN ST
4320921,118,131,NaN,West Main St,NaN,NaN,Laundry Rear,MA,ORANGE,1364,0.0,0.0,NaN,NaN,0.0,0.0,2016,131 West Main St
4414316,118,131,NaN,MAIN ST,NaN,NaN,NaN,MA,FALMOUTH,2540,0.0,50.0,NaN,NaN,0.0,0.0,2013,131 MAIN ST
4443766,118,131,NaN,PENROSE,ST,NaN,NaN,MA,SPRINGFIELD,1101,0.0,0.0,NaN,NaN,0.0,0.0,2012,131 PENROSE ST
4443838,118,131,NaN,CAMBRIDGE ST,NaN,NaN,NaN,MA,CAMBRIDGE,2141,0.0,0.0,NaN,NaN,0.0,0.0,2012,131 CAMBRIDGE ST